<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>3ec7e775-f92a-4689-a953-ace8967ed6b8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ScrumPoker.Web/ScrumPoker.Web.csproj" />
  </ItemGroup>

</Project>
